### ISSUE TITLE
Bring back autoprefixer

### ISSUE THREAD

**Issue by imagehat** [surprisehighway/generator-surprise#1]
CSS Nano strips all "unneccesary" vendor prefixes and does not add new prefixes to the file by default. 

I'd vote for bringing back autoprefixer. One option would be just to add the autoprefixer options and set the `add` flag. (Note that it only prefixes the minified version this way, which might be okay).

```
.pipe(gulp.dest(css_dir))
.pipe(rename({suffix: '.min'}))
.pipe(cssnano({
        autoprefixer: { browsers: [['last 2 versions', '> 1%', 'IE 9']], add: true}
    }))
.pipe(gulp.dest(css_dir))
```

Alternatively I _think_ we could run autoprefixer first, and disable the cssnano optimisation completely for the minified file, but haven't tested this out.

```
.pipe(prefix({
        browsers: ['last 2 versions', '> 1%', 'IE 9']
    }))
.pipe(gulp.dest(css_dir))
.pipe(rename({suffix: '.min'}))
.pipe(cssnano({
        autoprefixer: false
    }))
.pipe(gulp.dest(css_dir))
```

**Comment by rmknecht** [comment]
@imagehat merged a fix here: https://github.com/surprisehighway/generator-surprise/commit/a36dad0602ba46c17aa622bcbc89fd246cbb18e3

Looks like css-nano could have been massaging prefixes added by gulp-autoprefixer. The patch disables CSS Nano's prefixing so that we now rely on gulp-autoprefixer solely. 

Tested with the following sample of css: 

> .overkill-example {
	background:#f9f9f9;
	background:-moz-linear-gradient(top, #ffffff 0%, #f2f2f2 100%);
	background:-webkit-gradient(linear, left top, left bottom, color-stop(0%,#ffffff), color-stop(100%,#f2f2f2));
	background:-webkit-linear-gradient(top, #ffffff 0%, #f2f2f2 100%);
	background:-o-linear-gradient(top, #ffffff 0%, #f2f2f2 100%);
	background:-ms-linear-gradient(top, #ffffff 0%, #f2f2f2 100%);
	background:linear-gradient(to bottom, #ffffff 0%, #f2f2f2 100%);
	filter:progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffff', endColorstr='#f2f2f2',GradientType=0 );
}
